backend:
  name: git-gateway
  branch: main  # Replace with your default branch name if different

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.md"
        label: "Resume"
        name: "resume"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Content"
            name: "body"
            widget: "markdown"
