backend:
  name: github
  repo: devdave666/resume
  branch: main
  auth_endpoint: https://devdave666.github.io/resume/oauth.html

site_url: https://devdave666.github.io/resume/

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.md"
        label: "Resume"
        name: "resume"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
          
